version: '3.8'

services:
  agendador-tarefas:
    build: ../agendador-tarefas
    image: sindoval/agendador-tarefas:latest
    container_name: agendador-tarefas
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/db_agendador
      USUARIO_URL: http://usuario:8081/usuario

    depends_on:
      - mongo

  bff-agendador-tarefas:
    build: .
    image: sindoval/bff-agendador-tarefas:latest
    container_name: bff-agendador-tarefas
    ports:
      - "8084:8084"
    environment:
      USUARIO_URL: http://usuario:8081/usuario
      TAREFAS_URL: http://agendador-tarefas:8082/tarefas
      NOTIFICACAO_URL: http://notificacao:8083/email
      COMUNICACAO_URL: http://comunicacao:8085/comunicacao
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@admin.com}
      ADMIN_SENHA: ${ADMIN_SENHA:-123456}
      TZ: "America/Sao_Paulo"

  usuario:
    build: ../usuario
    image: sindoval/usuario:latest
    container_name: usuario
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_usuario
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

    env_file:
      - .env
    depends_on:
      - postgres

  comunicacao:
    build: ../comunicacao_api
    image: sindoval/comunicacao-api:latest
    container_name: comunicacao
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_comunicacao
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      NOTIFICACAO_URL: http://notificacao:8083/email
    depends_on:
      - postgres

  notificacao:
    build: ../notificacao
    image: sindoval/notificacao:latest
    container_name: notificacao
    ports:
      - "8083:8083"
    env_file:
      - .env
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_agendador

networks:
  default:
    driver: bridge