spring.application.name=bff-agendador

usuario.url=${USUARIO_URL:http://localhost:8081/usuario}
tarefas.url=${TAREFAS_URL:http://localhost:8082/tarefas}
notificacao.url=${NOTIFICACAO_URL:http://localhost:8083/email}
comunicacao.url=${COMUNICACAO_URL:http://localhost:8085/comunicacao}


admin.email=admin@admin.com
admin.senha=123456

cron.horario=0 0/5 * * * ?

server.port=8084
